### ISSUE TITLE
Inverted current channel tab

### ISSUE THREAD

**Issue by LoLei** [dylanaraps/birch#14]
### Discussion

This might just be personal preference, but I dislike the way of highlighting the current channel by inverting the colors, as it is done currently. This is a pet peeve of mine in general, having such a glaring element.

![current way](https://user-images.githubusercontent.com/6799467/75714877-2793ab80-5cd5-11ea-8aad-92d7f245bdaf.jpg "Current way")

I've [patched my fork](https://github.com/dylanaraps/birch/compare/master...LoLei:master) to use bold instead. It's less readable but more aesthetic IMO:

![2020-03-05_15-39](https://user-images.githubusercontent.com/9076894/75991969-93555e80-5ef7-11ea-96de-f81b266a000f.png)

What does the community think? What about underline?

![2020-03-05_15-42](https://user-images.githubusercontent.com/9076894/75992256-ff37c700-5ef7-11ea-97f2-ce618058bd0f.png)

**Comment by dylanaraps** [comment]
I think it's fine as-is. I've gone ahead and added `$BIRCH_STATUS` which you can set to a sequence for highlighting.

**Comment by dylanaraps** [comment]
Example: `BIRCH_STATUS='\e[31;1m' birch`

**Comment by LoLei** [comment]
Wow, great solution, thanks!
