### ISSUE TITLE
Feature wishlist

### ISSUE THREAD

**Issue by icyphox** [dylanaraps/birch#3]
- [x] Command line flag for specifying custom port
- [x] Multi-channel join at startup
- [x] Option to specify server username (not to be confused with the nickname)
- [x] Buffer list
- [x] Keyboard nav for buffers
- [x] ~~Respond to `VERSION`, `PING`, `ACTION`~~ Action done. Not going to bother with others.
- [x] A `/me` command
- [x] Nick highlight color
- [ ] Optional notifications
- [x] Send raw commands (`/r CMD` perhaps)
- [x] Nickname tab completion

**Comment by dylanaraps** [comment]
Buffer list is done.

**Comment by dylanaraps** [comment]
`/raw` is done.

**Comment by dylanaraps** [comment]
Keyboard nav for buffers is `ctrl+n` or `/next`.

**Comment by dylanaraps** [comment]
Added `-U` for server username.

**Comment by dylanaraps** [comment]
Nick completion is done (@<TAB>).

**Comment by dylanaraps** [comment]
I care not for notifications. Patches welcome.
